### ISSUE TITLE
Q: Combine with official PoE HAT

### ISSUE THREAD

**Issue by pproenca** [uugear/Witty-Pi-4#15]
Hello,

Can the Witty Pi 4 Mini be used with the official PoE HAT on a Raspberry Pi 4+? I am looking to manage power on a set schedule and would love to explore other functionalities the witty board offers.

**Comment by uugear** [comment]
Witty Pi 4 Mini doesn't support the official PoE HAT.

Witty Pi 4 Mini doesn't even have a DC/DC converter on board, and it can only accept 5V DC. 

The PoE HAT will power the Pi directly and that will bypass Witty Pi 4 Mini.
