### ISSUE TITLE
Can the Witty Pi be powered by an 8.4v lithium battery? Can the battery be charged and managed through Witty Pi?

### ISSUE THREAD

**Issue by yq3w** [uugear/Witty-Pi-4#20]
Can the Witty Pi be powered by an 8.4v lithium battery? Can the battery be charged and managed through Witty Pi?

**Comment by uugear** [comment]
Witty Pi 4 can be powered by an 8.4V Lithium battery. It can not charge the battery though.

Witty Pi 4 L3V7 can charge Lithium battery, but it only support 3.7V battery.
