### ISSUE TITLE
Question about the button on the HAT

### ISSUE THREAD

**Issue by webfinder42** [uugear/Witty-Pi-4#24]
Hello

I have bought two WittyPi 4 mini which sits on 2xRaspberry pi 3b+

I can turn them on via the button, but if I want them to turn off, they don't work?
I just want to know why you can't turn off your raspberry pi with 1 press of the button? or a long(er) press?

It seems that if I hold the button down for a long time, it "cuts" the power?
![button on Witty Pi](https://github.com/uugear/Witty-Pi-4/assets/133808858/af1c8c06-8375-4052-b89f-e3e3823d2f1d)

Is there a log so I can do some trace?

**Comment by uugear** [comment]
Turning off is done by the software, specifically by the daemon.sh script.
It seems your software has not been installed, or met some errors during the installation.
With software installed you can find the wittyPi.log file in software's directory.
