### ISSUE TITLE
Raspberry Pi 5 Support

### ISSUE THREAD

**Issue by rocketcrane** [uugear/Witty-Pi-4#25]
Hi! Could you update the software to support Raspberry Pi 5 with the Witty Pi 4 L3V7? Even though RPi 5 has a RTC already, it doesn't have Lithium-Ion battery management.

**Comment by uugear** [comment]
We have update the software to version 4.2, and now Witty Pi 4 (including Mini and L3V7) supports Raspberry Pi 5.
