### ISSUE TITLE
I2C_BUS set to 0 instead of 1

### ISSUE THREAD

**Issue by Jessseee** [uugear/Witty-Pi-4#38]
[Commit d5ad6a7
](https://github.com/uugear/Witty-Pi-4/commit/d5ad6a7067a3eed8f6c55e6d7a105caf1fecae80#diff-c56c39c5f1df9a37a693a4cd13a2718918cef448d60b6278025dfdd186eafa7dR12) replaces all calls to i2c functions with the hardcoded value `1` with the `I2C_BUS` variable. However, the variable is set to `0` by default. This currently breaks any existing installs trying to update from older versions of the software.

**Comment by uugear** [comment]
Thanks for the report. The commit e833c8d fixes it.

**Comment by Jessseee** [comment]
Thanks!
