### ISSUE TITLE
Witty Pi 4 L3V7: use of GPIO 17

### ISSUE THREAD

**Issue by xStatts** [uugear/Witty-Pi-4#7]
Hi there,

I'm planning on pairing the Witty Pi 4 L3V7 with an epaper display. When the display resets, the Pi sends a 20ms high signal on GPIO 17, which (to my understanding) the Witty Pi also uses to know if the Pi has switched on. Im wondering if the reset signal from the display may interfere with the Witty Pi if all it is doing is confirming that the Pi has switched on?

Thanks!

**Comment by uugear** [comment]
Witty Pi 4 uses GPIO-17 in both input and output mode. When Raspberry Pi is booting, Witty Pi's software sets GPIO-17 to input mode and wait for the SYS\_UP signal. However GPIO-17 also controlled by the MCU on Witty Pi 4 and can be driven to HIGH to light up the white LED.

Although the chance is rather small, it could still happen that when MCU drives GPIO-17 to LOW (to turn off white LED) and your epaper display sends high signal on GPIO-17. 20ms is very short and usually would not cause damage, but still it is not perfectly safe.

It would be better to change the pin used by Witty Pi 4. You may cut the trace at the back and link SYS\_UP to a different GPIO. The software needs to be modified too.
